### ISSUE TITLE
Create Releases

### ISSUE THREAD

**Issue by ghost** [Jazqa/adwaita-tweaks#1]
Thanks for your great work! For packagers, it would be easiest if you could create some releases for easy versioning in the OS.

**Comment by Jazqa** [comment]
Sure! I'll do this as soon as I can. I didn't think of it before as I got ~30 downloads when I posted this on Reddit. The OMG!Ubuntu mention came as a huge surprise.

**Comment by Jazqa** [comment]
Done. Your current package should still work.

**Comment by ghost** [comment]
Thanks, Jazqa!
