### ISSUE TITLE
Desktop font color 

### ISSUE THREAD

**Issue by EdiDD** [Jazqa/adwaita-tweaks#10]
When desktop icons are enabled font color is black and completely unreadable.

**Comment by Jazqa** [comment]
...and the exact opposite on the dark variant, seems like they are missing shadows. It's actually the base Adwaita theme doing that, but I'm on it and will commit the fix as soon as I have figured it out.

**Comment by EdiDD** [comment]
It works in gtk.css: 

.nautilus-desktop.nautilus-canvas-item {
    color: white;
    text-shadow: 1px 1px black;
}

but maybe there is a better way ?

**Comment by Jazqa** [comment]
Nope, that's the correct one. Found it exactly the second you posted.

**Comment by Jazqa** [comment]
I'll close this when I make the next release available, thanks a ton for the help! :)

**Comment by EdiDD** [comment]
I'm glad I could help
