### ISSUE TITLE
Unreadable file size after selection

### ISSUE THREAD

**Issue by EdiDD** [Jazqa/adwaita-tweaks#11]
There is no additional background (like in original adwaita) after file selection in bottom right corner. There is only black text on black text

**Comment by Jazqa** [comment]
The one in the bottom-right corner? I added a slight border to it on both dark and light variants.

![pic](http://i.imgur.com/XXkWLNC.png)

**Comment by EdiDD** [comment]
Yes it works now. Thank you. Two more things to perfection:
1. Changing nautilus background is not working in list view 

.nautilus-window {
        background #E6E6E6
}

2. Horizontal lines in original adwaita are quite cool. They are gone in list view.

**Comment by Jazqa** [comment]
Found the first one. Still looking for the horizontal lines.

```
.nautilus-window,
.nautilus-window .view {
background #E6E6E6
}
```

**Comment by EdiDD** [comment]
Nice, thanks

**Comment by Jazqa** [comment]
Ok, the .view alone has some problems, found a better solution (plus the horizontal lines).

```
.nautilus-window {
  background #E6E6E6
}

.nautilus-window treeview .view {
  background #E6E6E6
  border-bottom: 1px solid rgba(200, 200, 200, 1);
}
```

I'll push the changes as soon as I've applied it to the dark theme as well.

**Comment by Jazqa** [comment]
Done, reopen this if there's still something wrong with Nautilus. Also, thanks a ton!

**Comment by EdiDD** [comment]
Hmm... seems this change is not working at all.

**Comment by Jazqa** [comment]
Ohh? Weirdly it's working for me. Note that if the border color is too close to the background color, they are hard to distinguish.

![working](http://i.imgur.com/Pc4ovlM.png)

**Comment by EdiDD** [comment]
False alarm. It's working now. Good job  :)
