### ISSUE TITLE
Pie chart and other graphical legend not shown for drive properties in Nautilus

### ISSUE THREAD

**Issue by ocludo** [Jazqa/adwaita-tweaks#14]
Same problem as [this](https://github.com/lassekongo83/plano-theme/issues/17). GNOME 3.24 on Fedora 26.

**Comment by Jazqa** [comment]
Nice catch! It's just another element missing from Nautilus (like #10, #11 and #12). While I import the base GTK theme from Adwaita, the Nautilus-specific elements are not imported with the GTK theme and have to be reimplemented.

I'll fix it as soon as I get my hands on my GNOME machine.
