### ISSUE TITLE
LibreOffice Styles tabs and toggle switches in header bars

### ISSUE THREAD

**Issue by ocludo** [Jazqa/adwaita-tweaks#17]
This must be getting rather frustrating, but the tab headers in the LibreOffice Style selector appear to have empty space between them, and if a toggle switch appears in a header bar, its On position looks faded/disabled. Screenshots attached.

![screenshot-adwaita_tweaks-libreoffice_styles](https://user-images.githubusercontent.com/27003975/30740784-eadf0ed6-9f81-11e7-9714-291c97d4d47f.png)
![screenshot-adwaita_tweaks-tweak_tool](https://user-images.githubusercontent.com/27003975/30740790-f050e470-9f81-11e7-9f57-bf9cc119c63d.png)

**Comment by Jazqa** [comment]
I'm pretty sure I know what's causing them and it shouldn't take long to fix. Might take until tonight though as I don't have a working operating system at the moment as I'm in the process of (re)installing Arch.

**Comment by Jazqa** [comment]
I've fixed both of these. For some reason, Libreoffice's style selector remains somewhat large and can't be shrunk further, but at least it's working and looking good with the theme.
