### ISSUE TITLE
Tweak to Nautilus file list colors

### ISSUE THREAD

**Issue by markd89** [Jazqa/adwaita-tweaks#19]
Hi, 
Can you give me a clue if it is possible for me to add a tweak to your tweaks to change the color in the Nautilus file list. Right now there is a grey horizontal line line between each file. I want to change that color so it is the same as the background (making it invisible).

Any suggestion or clue would be great.
Thanks!!
Mark

**Comment by Jazqa** [comment]
Find the `gtk-3.0/gtk.css` and remove the **border-bottom** line from 

```
.nautilus-window treeview .view {
	color: #232729;
	background: #FFFFFF;
	border-bottom: 1px solid rgba(232, 232, 232, 1);
}
```

**Comment by markd89** [comment]
Perfect, thank you!!
