### ISSUE TITLE
Printer Details window in GNOME Settings missing header bar

### ISSUE THREAD

**Issue by ForgottenUmbrella** [Jazqa/adwaita-tweaks#5]
In `GNOME Shell` > `Activities Overview` > `Settings` > `Hardware section` > `Printers` > `Gear Icon beside a listed printer` > `Printer Details`: there is no header bar. This makes closing the window somewhat difficult, since the Close button is missing from the nonexistent header bar.

![printerdetailsescape](https://user-images.githubusercontent.com/14356244/27116920-23851d3e-5117-11e7-929b-5950a69971bf.png)

**Comment by Jazqa** [comment]
Hey! Thanks for filing the issue. Happen to know an easy way to add a "fake" printer? I can't access the window because I don't have any printers nearby.

EDIT: Figured it out, now to fix the bug.
EDIT 2: Fixed. Fetch & pull the repository, haven't added the fix to the releases yet.

**Comment by Jazqa** [comment]
I'll close this as I've fixed it. Just fetch & pull or re-clone the repository and you'll have the fixed version.
