### ISSUE TITLE
Openbox 

### ISSUE THREAD

**Issue by natemaia** [Jazqa/adwaita-tweaks#6]
Hello sir, first let me say thank you for what you did with adwaita. Genuinely a requirement for me as the base adwaita has colour issues with atom text editor (my preferred)
I am wondering if you have any interest including an openbox-3 theme.
I've written a fair bit of openbox themes and have a couple I've tweaked over time for the adwaita variants.

Would be awesome if you took a look at them and we could work something out.
I can make a pull request and will post a few photos here shortly, if that better suits you

Thanks for your time,
Nathaniel

**Comment by Jazqa** [comment]
Of course, I'd be happy to include an Openbox theme as long it's consistent with the rest of the theme. Regular Adwaita only supports gnome-shell, gtk-2 and gtk-3. Personally I'd be happy if this theme also worked as a way to get Adwaita (or an Adwaita-ish theme) on as many WMs and DEs as possible. It's nothing I'm going to focus on, but who knows, maybe I'll add Cinnamon, Xfce and MATE support one day.

Anyways, the Openbox will have to wait until tomorrow or the day after as today is very busy and tomorrow I'll be switching distirbution for something that works better with multiple DEs.

As a completely unrelated note (I've got no other way to reach people using the theme so I'll just ask here), I have a few ideas for the GNOME theme but I'm afraid I'm drifting too far from the regular Adwaita. What do you think about the round windows, should I make the corners 90°, a little less round than the current ones or keep them as is?

![corner](http://i.imgur.com/TXtLHYA.png)

**Comment by erikdubois** [comment]
that is super news - was following this thread

**Comment by natemaia** [comment]
That is the attitude I like to hear, no worries on the timing there is no rush. Like I said I'll just make a pull in the coming days so you can easily merge if you like it.

On the note about changes, personally I would love a move to less corner radius if that is something your thinking of. Myself being on openbox, which doesnt support rounded corners I prefer the 90° approach. Indeed it is difficult to know how other feel about this but the changes so far have been quite good, keep it rolling ;)

**Comment by natemaia** [comment]
So I have been rather busy the last few days but I got a start and figured I'd throw it here to see what you think.
A couple caveats, openbox doesn't really 'do' round. The window buttons are xbm so there isnt any (good) circular shapes that can be done without looking blocky.

I used a raised background an a dark border to get some feedback when hovering over window buttons.

I tried to match the buttons relatively well. Openbox can only match up so well, anything larger than 12x12px and the buttons render offset to the background, so I opted for smaller buttons.

I made the titlebar a bit larger than I normally would to try keeping it more consistent across gtk2-gtk3 apps. Totally open to suggestions and I'll throw a video or gif up if you want a better look

![adwaita1](https://user-images.githubusercontent.com/29465624/27987516-a47517f0-63c3-11e7-93a9-81eb73f996cd.png)

![adwaita2](https://user-images.githubusercontent.com/29465624/27987518-a8c7e8c8-63c3-11e7-8228-f0b25ec53068.png)

![2017-07-09-52_3600x1080_scrot](https://user-images.githubusercontent.com/29465624/27992397-c5bf0382-6448-11e7-919a-60b58a74ed87.png)

![2017-07-09-46_3600x1080_scrot](https://user-images.githubusercontent.com/29465624/27992398-c90aba40-6448-11e7-957e-50c16f73cc10.png)

![2017-07-08-29_3600x1080_scrot](https://user-images.githubusercontent.com/29465624/27987594-d73bbbb6-63c4-11e7-896d-781235183070.png)

**Comment by Jazqa** [comment]
Looks amazing and matches the GTK theme perfectly! Great job! I actually like your KDE-like window buttons way more than the regular Adwaita ones. However, I'm a consistency freak and think that the buttons should be, by default, the same across the themes (two solutions: either go with the ugly Adwaita buttons for the Openbox theme, or include these in the GTK theme). Personally, I'd be happy to include these buttons in the GTK theme.

**Comment by erikdubois** [comment]
i would not deviate too much from adwaita personally
you choose - consistency is key

**Comment by Jazqa** [comment]
Yeah. The whole point of the theme was to shrink down the original. I hope natemaia doesn't mind if the original Adwaita buttons are used instead. 

Besides that, I'll make the GTK corners just a tad bit less round (shrink the radius by two pixels or so) to make the smaller titlebars look better. After that, I'll just leave the GTK-3 and GNOME Shell themes alone and focus on other DEs, starting with Cinnamon.

**Comment by natemaia** [comment]
Haha,  my bad man. Now realise I totally screwed up the buttons, will fix them stat. :) 
Don't worry no harm done.. This was entirely error on my part as I really didn't research the actual buttons. I have had Gtk borders disabled for far too long being on openbox forgot how they even looked I was using catfish and pamac to go off and forgot to change my icon theme to make the buttons proper.
I agree consistency is key.

Anyhow, now that I know you're roughly happy with the layout and colour I'll make the base (white) variant tonight

**Comment by natemaia** [comment]
It's funny cause going with these buttons is so much better. I was struggling to make the other ones work, these are easy

**Comment by Jazqa** [comment]
Once again, great work! This is by far my favorite Openbox theme and I'm using it on all of my LXDE/Openbox machines now. Anyways, it's actually larger than the base theme, mind if I edit the size a bit for a release download? The menu border also looks weird on my setup (it looks way better on your setup) so I was thinking I'd try the menu with a bit more boring, default-like border, and it looks quite nice as well.

Anyways, I don't use Openbox that much so I don't know what I'm doing. Tell me what you think, we'll keep your version if you prefer that one! Thanks a lot for the awesome work.

![Dark](http://i.imgur.com/4oCdC0X.png)

![Light](http://i.imgur.com/uzbSyuT.png)

**Comment by natemaia** [comment]
@Jazqa I am happy you like it :)
If you want we can change the titlebar/header size for sure, I made them kinda huge (my opinion) in an attempt to match the references I used. 
The size of title text plays a part in how big the buttons and the titlebar not sure about LXDE but in openbox this is handled in the rc.xml, not much I can do from the theme end it just handles padding. 

I'm like what you have above if you want to go with that, it looks great!

As for the border issue, I am fine with you tweaking whatever to your liking. I may be incorrect and you were referring to the gaps and large bordering so this might be irrelevant 

The reason it looks different on your setup is because you must have compton set with transparent borders enabled. I don't like this because in combination with inactive-opacity and menu opacity, borders become super transparent

I don't use inactive opacity if you want just uncomment it 

Something like this in
~/.config/compton.conf
```
# Opacity
menu-opacity = 1;
frame-opacity = 1;
#inactive-opacity = 0.85;
inactive-opacity-override = false;
alpha-step = 0.03;

```

**Comment by natemaia** [comment]
Check out what happens when you crank the titlebar font size up, openbox is a strange cookie but I love it
![massive-fonts](https://user-images.githubusercontent.com/29465624/28033843-5c0ca6ac-6564-11e7-945c-8a7618afc5a2.png)

**Comment by natemaia** [comment]
Good work on the 1.3 release!
Very happy with it, gonna close this now.

**Comment by erikdubois** [comment]
Hi 
just to inform you that you need to change the pkgbuild on AUR
installed first adwaita-tweaks-git and then the non git version.
Then you get errors
Add line conflicts...
I thought I would see an adwaita tweaks dark?
Still under development?

**Comment by Jazqa** [comment]
@erikdubois, Dark and light versions are both available, the AUR packages are not made or maintained by me, but I'll have a look asap (if anyone can edit AUR packages, then I can fix it as soon as I've had lunch). Meanwhile, downloading them via the releases page on github and moving them to ~/themes (or /usr/share/themes) should do the trick.

**Comment by ghost** [comment]
@erikdubois, Please mark the AUR package as out of date if this occurs again. @Jazqa does not maintain it (though I'd be happy to give over maintainership if he cares). I do keep up with releases in an automated fashion but there's always a delay.

**Comment by Jazqa** [comment]
That was quick! Thanks a ton @ainola! If it's not much trouble, I'd be happy if you kept the AUR package as I'm not very familiar with AUR (I've packaged a few packages for Void but nothing else). I'll just flag it whenever I update ;)

**Comment by ghost** [comment]
On July 11, 2017 12:44:02 PM MDT, Jasu <notifications@github.com> wrote:
>That was quick! Thanks a ton @ainola! If it's not much trouble, I'd be
>happy if you kept the AUR package as I'm not very familiar with AUR
>(I've packaged a few packages for Void but nothing else). I'll just
>flag it whenever I update ;)

Not a problem at all. I should be able to update within the day of a release (I have daily notifications) but feel free to flag anytime.
