### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by Jazqa** [Jazqa/adwaita-tweaks#9]
Hello guys, I'm a fan of the gradient title bar and I've personally used it for a while. However, the point of the theme was to resemble the original Adwaita as much as possible, which is why I have not commited the change to Github. Before starting to work on the metacity theme for Cinnamon and MATE, I'd like to hear your opinions on the gradient title bar.

Active Nautilus window now:
![default](http://imgur.com/A7N0YBA.png)

Active Nautilus window with a gradient title bar:
![gradient](http://imgur.com/OivVuPt.png)

**Comment by natemaia** [comment]
I think that looks great, like anodised aluminium or something

**Comment by EdiDD** [comment]
Nice,
Do you think about setting gray background (like when window is inactive). It is not so glaring (like this default white) and friendlier to read, but it would still be light theme. How to achieve this ?

**Comment by Jazqa** [comment]
@EdiDD, If you mean the window background (not the titlebar), then it's changed on a program basis. The white background in the picture would be changed via

```
.nautilus-window {
	background: #FFFFFF;
}
```

I'm sticking with the default for now, I could turn the brightness of the white down a bit though.

**Comment by EdiDD** [comment]
Thanks, this is exactly what I need.
